# Generated by Django 5.0.3 on 2024-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('headquarter', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.BooleanField(default=False)),
                ('maintenance', models.DateField()),
            ],
        ),
    ]
